apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: convertx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: convertx.justindesio.com
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - convertx.justindesio.com
      secretName: convertx-tls
  rules:
    - host: convertx.justindesio.com
      http:
        paths:
          - backend:
              service:
                name: convertx
                port:
                  number: 3000
            path: /
            pathType: Prefix
