apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-990prep-staging
resources:
  - ../../base/990prep
  - namespace.yaml
patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
images:
  - name: registry.gitlab.com/justin-de-sio/990prep
    newTag: "staging-39df9ec3"
