apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:cmeqPq2jduvzK3QuKNpgEb9zpxp79fRKwUsVkBY1k2FlLEMREo3ku/CH8xRjryXin3XImloGZVy3+V17pISZ0wQc2TeQHBibwGWyT8/XLb+b+fTuFlEcZ4TcYKf9aG66rPcT/6/y01NX8OSjRXV3tK+eNMizxDSu9Z5zFY5hT7oS2v4SO1wS4qwRipwgmvN3k5K3tbKQG5X8vpWfRr4uYLgQKroI1ERflsK6gAOEK9IwnnftDOdkLUWufLSyydpkqTbzVupYesWnbySuQwrMGAW6WcViFZey33XMZHK7Hy4KJbly9GWjXXcV38cuaI+sAqYvQ1grtUSoqq2RGLhH4UKHk/jfCp2iyl5WM9OIU+g5/EEOeqx4DS25iwnFtxGykbWaX9vDt+1kU3YaE99Khi3bfAGyr3t/QA/nCXPCbcgiWXRmDHgNig==,iv:KafbjDukxh8ez8JUGheqXgbT45bJc1Pp/v8vXhlxi+s=,tag:oH1V931cXHAWwMsVSAOdVg==,type:str]
kind: Secret
metadata:
    name: gitlab-registry-secret
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJck1uK3gvNmp4ODFORUJF
            RHYrcHNRVFZzOEp3NmUvcHIxN2dmdFRHaXhvClZYdCtOYU5ScUhXUXB0N1BGOUQw
            UHRyR0I4c1JPbkpVWk9DQnp6Y3ZCS28KLS0tIEhoZ1VIaUJTQ1VFcVdTKytYNGkz
            b0tDdWtSNVhBL2YwMTJ4R0J4MTdNY1kK39sFMImXfd9gqqjt90QRLFBvc8qSPahH
            jAcQIR6Jl6fFIDhO/bB5DkZ74dVVQ5be/xlJCgfc0VErdYnpNI6Onw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T08:22:05Z"
    mac: ENC[AES256_GCM,data:/ZZ8Uzn11uSk7ifpGDfQswoTqdkdhK5HLc7Ug2acamfAKK0KruPXQRSPY6YpWtZDz2HE38ycxs/1P4a4CDuDQgwL6vcW0D3vEL81YVbvq92sgnHnUczOHW6OS3FwQj+fVJPbdJWHlkpOaZZePUvXqL2ltbitdoxNfYQSKFvM9S8=,iv:WQBiAPrQiWh/Pv2V9clhNo8rea953mtOyaF/DsC8Z8I=,tag:3yYTepWqhpwKzMiXPD9iyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
