---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: 990prep-app
  namespace: flux-system
spec:
  digestReflectionPolicy: Always
  interval: 1m0s
  filterTags:
    extract: ""
    pattern: ^latest$
  imageRepositoryRef:
    name: 990prep-app
  policy:
    alphabetical:
      order: desc
