apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mazanoke
  annotations:
    external-dns.alpha.kubernetes.io/hostname: compress.justindesio.com
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - compress.justindesio.com
      secretName: mazanoke-tls
  rules:
    - host: compress.justindesio.com
      http:
        paths:
          - backend:
              service:
                name: mazanoke
                port:
                  number: 80
            path: /
            pathType: Prefix
