apiVersion: v1
kind: ConfigMap
metadata:
  name: env-var
data:
  PUBLIC_SUPABASE_URL: https://buagjkanixyraclthyqk.supabase.co
  PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1YWdqa2FuaXh5cmFjbHRoeXFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNzAxMDIsImV4cCI6MjA3NDY0NjEwMn0.LtQBeOFoD9CiQ-cjl5r9H0vIqw8FPf5nLkoSfZjtgJs
  PUBLIC_POSTHOG_KEY: phc_TkDz9rn7gojZJvDWNgjdxbnN4T2TKPVomcOf8XjpZXY
  PUBLIC_POSTHOG_HOST: https://omega.justindesio.com
  PUBLIC_TIKTOK_PIXEL_ID=D5KFD7RC77UDR18JCSP0
  NODE_ENV: production
  PORT: "8080"
  ORIGIN: https://990prep.com
