apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-990prep
  name: app-990prep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-990prep
  strategy: {}
  template:
    metadata:
      labels:
        app: app-990prep
    spec:
      containers:
        - image: registry.gitlab.com/justin-de-sio/990prep:latest@sha256:5b8c9cbca1398116ed734f9972607ce3d9106dc5d7709c58a35d0a372319f0a4 # {"$imagepolicy": "flux-system:990prep-app"}
          name: app-990prep
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 1
          envFrom:
            - secretRef:
                name: secret-env
            - configMapRef:
                name: env-var
          resources:
            requests:
              memory: "64Mi"
            limits:
              memory: "256Mi"
      imagePullSecrets:
        - name: gitlab-registry-secret
