apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-990prep
  name: app-990prep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-990prep
  strategy: {}
  template:
    metadata:
      labels:
        app: app-990prep
    spec:
      containers:
        - image: registry.gitlab.com/justin-de-sio/990prep:latest@sha256:801611d36cd37ee04a3f28b9625b30a7fdb16832da48df7e029f1615adfc6baf
          name: app-990prep
          envFrom:
            - secretRef:
                name: secret-env
            - configMapRef:
                name: env-var
          resources: {}
      imagePullSecrets:
        - name: gitlab-registry-secret
