apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-990prep
  name: app-990prep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-990prep
  strategy: {}
  template:
    metadata:
      labels:
        app: app-990prep
    spec:
      containers:
        - image: registry.gitlab.com/justin-de-sio/990prep:latest@sha256:083125f48cee5c2f30be32dcd46e42c71c86a6e725efaabdd7b76bf5de4f8c21 # {"$imagepolicy": "flux-system:990prep-app"}
          name: app-990prep
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 1
          envFrom:
            - secretRef:
                name: secret-env
            - configMapRef:
                name: env-var
          resources:
            requests:
              memory: "64Mi"
            limits:
              memory: "256Mi"
      imagePullSecrets:
        - name: gitlab-registry-secret
