apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-990prep
  name: app-990prep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-990prep
  strategy: {}
  template:
    metadata:
      labels:
        app: app-990prep
    spec:
      containers:
        - image: registry.gitlab.com/justin-de-sio/990prep:latest
          name: app-990prep
          envFrom:
            - secretRef:
                name: secret-env
            - configMapRef:
                name: env-var
          resources: {}
      imagePullSecrets:
        - name: gitlab-registry-secret
