apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-990prep
  name: app-990prep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-990prep
  strategy: {}
  template:
    metadata:
      labels:
        app: app-990prep
    spec:
      containers:
        - image: registry.gitlab.com/justin-de-sio/990prep:latest@sha256:c68be73b3aea3a103654f489d9b9d39616214d4bbbea31ec57a3c8bb7359a9f9
          name: app-990prep
          readinessProbe:
            httpGet:
              path: /heath
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 1
          envFrom:
            - secretRef:
                name: secret-env
            - configMapRef:
                name: env-var
          resources:
            requests:
              memory: "64Mi"
            limits:
              memory: "256Mi"
      imagePullSecrets:
        - name: gitlab-registry-secret
