apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-990prep
  name: app-990prep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-990prep
  strategy: {}
  template:
    metadata:
      labels:
        app: app-990prep
    spec:
      containers:
        - image: registry.gitlab.com/justin-de-sio/990prep:latest:@sha256:2950c2ef2364da97986a729a3937fb7142d1d8f8d50b555ff95379969fb3d61e
          name: app-990prep
          envFrom:
            - secretRef:
                name: secret-env
            - configMapRef:
                name: env-var
          resources: {}
      imagePullSecrets:
        - name: gitlab-registry-secret
