apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-990prep
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - gitlab-registry-secret.yaml
  - deployment.yaml
  - service.yaml
