apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    tunnel: homelab

    credentials-file: /etc/cloudflared/creds/credentials.json

    metrics: 0.0.0.0:2000
    no-autoupdate: true

    ingress:
    - hostname: linkding.justindesio.com
      service: http://linkding.linkding.svc.cluster.local:9090

    - hostname: cloud.justindesio.com
      service: http://nextcloud.nextcloud.svc.cluster.local:8080

    - hostname: video.justindesio.com
      service: http://jellyfin.media.svc.cluster.local:80

    - hostname: tv.justindesio.com
      service: http://jellyfin-vue.media.svc.cluster.local:80

    - hostname: dashboard.justindesio.com
      service: http://homarr.dashboard.svc.cluster.local:7575

    # This rule matches any traffic which didn't match a previous rule, and responds with HTTP 404.
    - service: http_status:404
