apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - linkding
  - media
  - homarr
  # - nextcloud
  - pgadmin
  # - immich
  - n8n
  - homeassistant
  - 990prep
  - gitlab-runner
  - stirling-pdf
  - convertx
