apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - longhorn
  - cert-manager
  - 990prep-registry-secret.yaml
  - 990prep-image-repository.yaml
  - 990prep-image-policy.yaml
