apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-990prep
resources:
  - ../../base/990prep
  - namespace.yaml
images:
  - name: registry.gitlab.com/justin-de-sio/990prep
    newTag: "v1.2.6"
